### ISSUE TITLE
after change task

### ISSUE THREAD

**Issue by ZiskaH** [antest1/GotoBrowser#21]
Thank you for the nice browser.

I use it with OnePlus7 Pro, but after switching the task of the mobile phone to another task, I come back to this app, and when I try to move to another page in the game, the screen stays black. (Home port → Supply etc.)

I confirmed that this problem does not occur with Mi Mix 2 (android8) which I used before.
Is it an inherent symptom by android9?
Please let me know if there is a solution. Thank you.

**Comment by NoxArt** [comment]
Hi, does it stay black forever?
I observed 3 possible behaviors when switching back (Android 9 / OneUI)
1) Loads full to a working KC
2) Loads to a black screen ... after a while it changes to a loading screen (authentication probably still valid) and loads. Sometimes this takes a long time, but I _think_ it always loaded. Or at least almost always
3) Loads to a blank page saying
^ this applies to the Nitrabbit provider. It would be good to state which are you using, maybe there are differences?

It seems to me that the chance between 1 and 2 is largely government by how much free memory is available ... and it (for some reason) has to be much more than KC/GTB would actually use. It works best after device restart.
Chance between 2 and 3 seems to be mostly about how long you haven't interacted with the game, so that the login would expire

**Comment by antest1** [comment]
I'll check about this issue.
Does it not stop when you don't switching to the other task?
(maybe caused by interruption while loading the resources in webview)
