### ISSUE TITLE
Background issue

### ISSUE THREAD

**Issue by raltscn** [antest1/GotoBrowser#29]
Once I lock the smartphone when in the middle of battle,
for a while, when I unlock the srceen and I find the battle animation was stopped in many cases.

**Comment by antest1** [comment]
I'll check about the issue. 
Maybe due to the timer does not resumed?

It would be help to know me what devices and android version are you using.

**Comment by raltscn** [comment]
Thank you for replying me, and my two devices also has this issue:
1. SUMSUNG NOTE9(SM-N9600) with android 9
2. Nokia 5.1 plus(X5) with android 8.1

**Comment by NoxArt** [comment]
I had this happen to me too: Samsung Note 8 Android 9
I _think_ it also happened when I switched from the app to home screen and back

**Comment by raltscn** [comment]
Yes, swith other app for a while and back also cause it.(sometimes)

**Comment by laplamgor** [comment]
This is related to system webview (chromium) throttling.

The default behavior of Chromium (at least for version >57) is to throttle both timer tick interval and the CPU time budget. Therefore, timer-based animation (most animation in KC) will end later than it should. Using up all the budget (e.g. loading a Chuha screen during a battle) will cause it to pause completely.
https://developers.google.com/web/updates/2017/03/background_tabs

One possible solution is to use crosswalk instead of webview. It will solve most system-level throttling of webview (also the FPS issue in issue https://github.com/antest1/GotoBrowser/issues/17). The behavior of crosswalk in background is running same x1.0 timer speed, but lowered to 30fps. CPU limit seems to be application-level.

**Comment by laplamgor** [comment]
Just a random thought. 
The background CPU throttling limit can be worked around by implementing a "PictureInPicture" mode. Launching a PiP window will theoretically remove the background CPU time limit even if the main app is still minimized.

If you like this approach, I will try to work on it in Feb.

**Comment by raltscn** [comment]
thq for picture-in-picture mode
it‘s seems working good right now
