### ISSUE TITLE
Sound Issue: Unable to hear voice/sound effects, only BGM

### ISSUE THREAD

**Issue by Candy-Sama** [antest1/GotoBrowser#52]
Hi Devs!
I'm having an issue where I cannot hear Voice nor Sound Effects, but only BGM.

Steps to replicate:
1) Enable kcanotify
2) Enter GotoBrowser as per normal
3) Pressed Start, broadcast mode is disabled

Solutions tried:
- Restarting App/Phone
- Muted SFX and Voice, restarted App and enabled volume
- Muted SFX (Voice in the second run), and restarted App and enabled volume
- Muted all, restarted App and unmuted

Phone: Redmi Note 6 Pro
System: Android Ver. 9 PKQ1.180904.001

**Comment by Candy-Sama** [comment]
While I'm on this:
The app seems to cancel out other apps like Spotify and Soundcloud, I can't seem to play music because of that :(

**Comment by antest1** [comment]
You may try to clear the cache multiple times and restart the app (without kcanotify) to make sure the resources can be downloaded properly.
Also, if you are using both kcanotify and GotoBrowser, I recommend to use the passive sniffer (from kcanotify settings - sniffer settings) with broadcast mode enabled in GotoBrowser for the stable play.

Due to the android default behavior (as GotoBrowser works as "Browser") it cannot be played at the same time.
SFX and voice does not affected to this behavior, but you mush disable the BGM in the game to listen the music together.

**Comment by Candy-Sama** [comment]
I'm so sorry, I didn't realise that there was a clear cache option - it's fine now!
Thank you!!

Also, I did the work around you mentioned, it works! Thank you for the help!

Thank you very much for the quick response!

I believe you could mark this case as closed now! (I hope its all good now)
